version: '3.8'

services:
  maildev:
    image: maildev/maildev
    container_name: kibin_maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    container_name: kibin_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9000:8080"
    command: start-dev
